version: "3.7"
services:
  skinic-db:
    image: "mysql:8"
    container_name: dbDocumentCronjob
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cronjob_db
      MYSQL_USER: cronjob_db_admin
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - dbDocumentCronjobNetwork
networks:
    dbDocumentCronjobNetwork: